geekshop/adminapp/urls.py
from django.urls import path, include
import adminapp.views.user_views as user
import adminapp.views.category_views as category
import adminapp.views.product_views as product

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user.UserCreateView.as_view(), name='user_create'),
    path('users/read/', user.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', user.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', user.UserDeleteView.as_view(), name='user_delete'),


    path('categories/', include([
        path('create/', category.CategoryCreateView.as_view(
            extra_context={'title': 'админка/создание'}), name='category_create'),
        path('read/', category.CategoryListView.as_view(
            extra_context={'title': 'админка/категории'}), name='categories'),
        path('update/<int:pk>/', category.CategoryUpdateView.as_view(
            extra_context={'title': 'админка/редактирование'}), name='category_update'),
        path('delete/<int:pk>/', category.CategoryDeleteView.as_view(
            extra_context={'title': 'админка/удаление'}), name='category_delete'),
    ])),

    path('products/', include([
        path('create/category/<int:pk>/', product.ProductCreateView.as_view(), name='product_create'),
        path('read/category/<int:pk>/', product.ProductListView.as_view(
            extra_context={'title': 'админка/товары категории'}), name='products'),
        path('read/<int:pk>/', product.ProductDetailView.as_view(
            extra_context={'title': 'админка/просмотр товара'}), name='product_read'),
        path('update/category/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
        path('delete/category/<int:pk>/', product.ProductDeleteView.as_view(), name='product_delete'),
    ])),
]

geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'
urlpatterns = [
    path('view/', basket, name='view'),
    path('add/<int:pk>', basket_add, name='add'),
    path('remove/<int:pk>', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('admin/', include('adminapp.urls', namespace='admin')),  # admin.site.urls),
    path('contact/', mainapp.contact, name='contact'),
    path('shop/', include('mainapp.urls', namespace='shop')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('products/', include('mainapp.urls', namespace='products')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
# from mainapp.views import products, contact, product
import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(verbose_name='Категория активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='Описание продукта', blank=True)
    price = models.DecimalField(verbose_name='Цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='Продукт активен', default=True)

    def __str__(self):
        return f"{self.name}{self.category.name}"

geekshop/mainapp/views.py
from django.shortcuts import render
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
from django.shortcuts import get_object_or_404
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def main(request):
    title = 'магазин'
    products = Product.objects.all()
    basket = get_basket(request.user)
    content = {'title': title, 'products': products, 'basket': basket}
    return render(request, 'mainapp/shop.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user). \
        order_by('product__category')

    content = {
        'title': title,
        'basket': basket_items,
    }
    return render(request, 'basketapp/basket.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(category__is_active=True,
                                              is_active=True).order_by('price')
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__is_active=True,
                                              is_active=True).order_by('price')
        paginator = Paginator(products, 2)  # per_page=2
        try:
            # page() — позволяет получить содержимое страницы по номеру:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)  # total number of pages

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', content)


def contact(request):
    title = 'конакты'
    basket = get_basket(request.user)
    content = {'title': title, 'basket': basket}
    return render(request, 'mainapp/contact.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
           class="{% if request.resolver_match.kwargs.pk == 0 %}
                active
              {% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
               {# |add:'0' -  «плюс ноль», но при этом тип меняется со строки на число  #}
                  active
                {% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% block menu %}
    <a href="{% url 'main' %}" class="logo"></a>

    <ul class="menu">
        <li><a href="{% url 'main' %}"
               class="{% if request.resolver_match.url_name == 'main' %} active {% endif %}">главная</a>
        </li>
        <li>
            <a href="{% url 'products:index' %}"
               class="{% if request.resolver_match.namespace == 'products' %} active {% endif %}">продукты
            </a>
        </li>
        <li><a href="{% url 'contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %} active {% endif %}">контакты</a>
        </li>
    </ul>

    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin:users' %}">Админка</a>
        </li>
    {% else %}
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'auth:login' %}">войти</a>
            </li>
        {% endif %}
    {% endif %}

    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:logout' %}">выйти</a>
        </li>
    {% endif %}


    <a href="#" class="search"></a>
    <a href="{% url 'basket:view' %}" class="basket">
  <span>
    {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб
        ({{ basket.0.total_quantity }} шт)
    {% endif %}
  </span>
    </a>



{% endblock %}