geekshop/adminapp/urls.py
from django.urls import path, include
import adminapp.views.user_views as user
import adminapp.views.category_views as category
import adminapp.views.product_views as product

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', user.UserCreateView.as_view(), name='user_create'),
    path('users/read/', user.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', user.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', user.UserDeleteView.as_view(), name='user_delete'),


    path('categories/', include([
        path('create/', category.CategoryCreateView.as_view(
            extra_context={'title': 'админка/создание'}), name='category_create'),
        path('read/', category.CategoryListView.as_view(
            extra_context={'title': 'админка/категории'}), name='categories'),
        path('update/<int:pk>/', category.CategoryUpdateView.as_view(
            extra_context={'title': 'админка/редактирование'}), name='category_update'),
        path('delete/<int:pk>/', category.CategoryDeleteView.as_view(
            extra_context={'title': 'админка/удаление'}), name='category_delete'),
    ])),

    path('products/', include([
        path('create/category/<int:pk>/', product.ProductCreateView.as_view(), name='product_create'),
        path('read/category/<int:pk>/', product.ProductListView.as_view(
            extra_context={'title': 'админка/товары категории'}), name='products'),
        path('read/<int:pk>/', product.ProductDetailView.as_view(
            extra_context={'title': 'админка/просмотр товара'}), name='product_read'),
        path('update/category/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
        path('delete/category/<int:pk>/', product.ProductDeleteView.as_view(), name='product_delete'),
    ])),
]

geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('admin/', include('adminapp.urls', namespace='admin')),  # admin.site.urls),
    path('contact/', mainapp.contact, name='contact'),
    path('shop/', include('mainapp.urls', namespace='shop')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('products/', include('mainapp.urls', namespace='products')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views/category_views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from adminapp.forms import ProductCategoryEditForm
from mainapp.models import ProductCategory

from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls.base import reverse_lazy


# def category_create(request):
#     title = 'категории/создание'
#     if request.method == 'POST':
#         new_category = ProductCategoryEditForm(request.POST, request.FILES)
#         if new_category.is_valid():
#             new_category.save()
#             return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         new_category = ProductCategoryEditForm()
#     content = {
#         'title': title,
#         'update_form': new_category
#     }
#     return render(request, 'adminapp/category_form.html', content)

class CategoryCreateView(CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('admin:categories')


# def categories(request):
#     title = 'админка/категории'
#     categories_list = ProductCategory.objects.all()
#     content = {
#         'title': title,
#         'objects': categories_list
#     }
#     return render(request, 'adminapp/categories.html', content)

class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'


# def category_update(request, pk):
#     title = 'категории/редактирование'
#
#     category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin:category_update', args=[category.pk]))
#     else:
#         edit_form = ProductCategoryEditForm(instance=category)
#
#     content = {
#         'title': title,
#         'update_form': edit_form
#     }
#     return render(request, 'adminapp/category_form.html', content)

class CategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('admin:categories')


# def category_delete(request, pk):
#     title = 'категории/удаление'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         category.is_active = 'False'
#         category.save()
#         return HttpResponseRedirect(reverse('admin:categories'))
#     content = {
#         'title': title,
#         'category_to_delete': category
#     }
#     return render(request, 'adminapp/category_delete.html', content)


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')

    def form_valid(self, form):
        success_url = self.get_success_url()
        # self.object.delete()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

geekshop/adminapp/views/product_views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from adminapp.forms import ProductEditForm
from mainapp.models import ProductCategory, Product
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls.base import reverse_lazy


# def product_create(request, pk):
#     title = 'продукт/создание'
#     category = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('admin:products', args=[category.pk]))
#     else:
#         product_form = ProductEditForm(initial={'category': category})
#     content = {'title': title,
#                'update_form': product_form,
#                'category': category
#                }
#
#     return render(request, 'adminapp/product_form.html', content)

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('admin:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/создание'
        context['category'] = self.kwargs['pk']
        return context


# def products(request, pk):
#     title = 'админка/продукт'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     products_list = Product.objects.filter(category__pk=pk).order_by('name')
#     content = {
#         'title': title,
#         'category': category,
#         'objects': products_list
#     }
#     return render(request, 'adminapp/products.html', content)

class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs['pk']).order_by('price')


# def product_read(request, pk):
#     title = 'продукт/подробнее'
#     product = get_object_or_404(Product, pk=pk)
#     content = {'title': title, 'object': product, }
#
#     return render(request, 'adminapp/product_read.html', content)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


# def product_update(request, pk):
#     title = 'продукт/редактирование'
#
#     edit_product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin:product_update', args=[edit_product.pk]))
#     else:
#         edit_form = ProductEditForm(instance=edit_product)
#
#     content = {'title': title,
#                'update_form': edit_form,
#                'category': edit_product.category
#                }
#
#     return render(request, 'adminapp/product_form.html', content)

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('admin:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/редактирование'
        context['category'] = self.object.category.pk
        return context


# def product_delete(request, pk):
#     title = 'продукт/удаление'
#
#     product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         product.is_active = False
#         product.save()
#         return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))
#
#     content = {'title': title, 'product_to_delete': product}
#
#     return render(request, 'adminapp/product_delete.html', content)

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin:categories')

    def form_valid(self, form):
        success_url = self.get_success_url()
        # self.object.delete()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/удаление'
        return context

geekshop/adminapp/views/user_views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls.base import reverse_lazy

from adminapp.forms import ShopUserAdminEditForm
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser


# def user_create(request):
#     title = 'пользователи/создание'
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#
#     content = {'title': title, 'update_form': user_form}
#
#     return render(request, 'adminapp/user_form.html', content)

class UserCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_form.html'
    success_url = reverse_lazy('admin:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/создание'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#     user_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     content = {
#         'title': title,
#         'objects': user_list
#     }
#     return render(request, 'adminapp/user_list.html', content)

class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/user_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'
        return context


# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserAdminEditForm(instance=edit_user)
#
#     content = {'title': title, 'update_form': edit_form}
#
#     return render(request, 'adminapp/user_form.html', content)

class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'adminapp/user_form.html'
    success_url = reverse_lazy('admin:users')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/редактирование'
        return context


# def user_delete(request, pk):
#     title = 'пользователи/удаление'
#
#     user = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         # user.delete()
#         # вместо удаления сделаем неактивным
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin:users'))
#
#     content = {'title': title, 'user_to_delete': user}
#
#     return render(request, 'adminapp/user_delete.html', content)

class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users')

    def form_valid(self, form):
        success_url = self.get_success_url()
        # self.object.delete()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/удаление'
        return context

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{#        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">#}
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>

<body>
<div class="container">
    <div class="h2 text-center head">
        Админка
    </div>

    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href={% url 'admin:category_create' %}>
                новая категория
            </a>
        </button>

        {% for object in object_list %}
            <div class="category_record
                {% if not object.is_active %}
                    not_active
                {% endif %}">

            <div class="category_name">
                {{ object.name|title }}
            </div>
                <div class="category_actions">
                    <button>
                        <a href={% url 'admin:products' object.pk %}>
                            товары категории
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:category_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:category_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ object.name }}
        {% if object.name %}
            ({{ object.name|title }})
        {% endif %}
        ?
        <form action="{% url 'admin:category_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:categories' %}">
            к списку категорий
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ object.name }}
        {% if object.name %}
            ({{ object.name|title }})
        {% endif %}
        ?
        <form action="{% url 'admin:product_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' object.category_id %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_form.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:products' category %}">
            к списку продуктов
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="{{ object.image|media_folder_products }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.category.pk %}>
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:products' category.pk%}">
            к списку продуктов
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href={% url 'admin:product_create' object_list.0.category_id %}>
                новый продукт
            </a>
        </button>

        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="{{ object.image|media_folder_products }}"
                     alt="{{ object.name }}">

                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href={% url 'admin:product_read' object.pk %}>
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:product_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:product_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ object.username }}
        {% if object.first_name %}
            ({{ object.first_name|title }}
            {% if object.last_name %}
                {{ object.last_name|title }}
            {% endif %})
        {% endif %}
        ?
        <form action="{% url 'admin:user_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:users' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:users' %}">
            к списку пользователей
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'admin:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in object_list %}
            <div class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img src="{{ object.avatar|media_folder_users }}"
                        alt="{{ object.username }}" width="150" />
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    {% if object.first_name %}
                        <b>{{ object.first_name|title }}</b>
                        {% if object.last_name %}
                            <p>{{ object.last_name|title }}</p>
                        {% endif %}
                    {% endif %}
                </div>

                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>

                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>

                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>


            <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'admin:user_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:user_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
        {% endfor%}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:users' %}">
            к списку пользователей
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'admin:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in objects %}
            <div class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
                        alt="{{ object.username }}" width="150" />
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    {% if object.first_name %}
                        <b>{{ object.first_name|title }}</b>
                        {% if object.last_name %}
                            <p>{{ object.last_name|title }}</p>
                        {% endif %}
                    {% endif %}
                </div>

                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>

                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>

                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>


            <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'admin:user_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:user_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
        {% endfor%}
    </div>
{% endblock %}