geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'
urlpatterns = [
    path('view/', basket, name='view'),
    path('add/<int:pk>', basket_add, name='add'),
    path('remove/<int:pk>', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('admin/', include('adminapp.urls', namespace='admin')),  # admin.site.urls),
    path('contact/', mainapp.contact, name='contact'),
    path('shop/', include('mainapp.urls', namespace='shop')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('products/', include('mainapp.urls', namespace='products')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
# from mainapp.views import products, contact, product
import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    is_active = models.BooleanField(verbose_name='Категория активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='Описание продукта', blank=True)
    price = models.DecimalField(verbose_name='Цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='Продукт активен', default=True)

    def __str__(self):
        return f"{self.name}{self.category.name}"

geekshop/adminapp/views/product_views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from adminapp.forms import ProductEditForm
from mainapp.models import ProductCategory, Product
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls.base import reverse_lazy


# def product_create(request, pk):
#     title = 'продукт/создание'
#     category = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.FILES)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('admin:products', args=[category.pk]))
#     else:
#         product_form = ProductEditForm(initial={'category': category})
#     content = {'title': title,
#                'update_form': product_form,
#                'category': category
#                }
#
#     return render(request, 'adminapp/product_form.html', content)

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('admin:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/создание'
        context['category'] = self.kwargs['pk']
        return context


# def products(request, pk):
#     title = 'админка/продукт'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     products_list = Product.objects.filter(category__pk=pk).order_by('name')
#     content = {
#         'title': title,
#         'category': category,
#         'objects': products_list
#     }
#     return render(request, 'adminapp/products.html', content)

class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs['pk']).order_by('price')


# def product_read(request, pk):
#     title = 'продукт/подробнее'
#     product = get_object_or_404(Product, pk=pk)
#     content = {'title': title, 'object': product, }
#
#     return render(request, 'adminapp/product_read.html', content)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


# def product_update(request, pk):
#     title = 'продукт/редактирование'
#
#     edit_product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin:product_update', args=[edit_product.pk]))
#     else:
#         edit_form = ProductEditForm(instance=edit_product)
#
#     content = {'title': title,
#                'update_form': edit_form,
#                'category': edit_product.category
#                }
#
#     return render(request, 'adminapp/product_form.html', content)

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_form.html'
    success_url = reverse_lazy('admin:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/редактирование'
        context['category'] = self.object.category.pk
        return context


# def product_delete(request, pk):
#     title = 'продукт/удаление'
#
#     product = get_object_or_404(Product, pk=pk)
#
#     if request.method == 'POST':
#         product.is_active = False
#         product.save()
#         return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))
#
#     content = {'title': title, 'product_to_delete': product}
#
#     return render(request, 'adminapp/product_delete.html', content)

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('admin:categories')

    def form_valid(self, form):
        success_url = self.get_success_url()
        # self.object.delete()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/удаление'
        return context

geekshop/mainapp/views.py
from django.shortcuts import render
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
from django.shortcuts import get_object_or_404
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def main(request):
    title = 'магазин'
    products = Product.objects.all()
    basket = get_basket(request.user)
    content = {'title': title, 'products': products, 'basket': basket}
    return render(request, 'mainapp/shop.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user). \
        order_by('product__category')

    content = {
        'title': title,
        'basket': basket_items,
    }
    return render(request, 'basketapp/basket.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.filter(category__is_active=True,
                                              is_active=True).order_by('price')
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__is_active=True,
                                              is_active=True).order_by('price')
        paginator = Paginator(products, 2)  # per_page=2
        try:
            # page() — позволяет получить содержимое страницы по номеру:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)  # total number of pages

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'basket': basket,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }
    return render(request, 'mainapp/products.html', content)


def contact(request):
    title = 'конакты'
    basket = get_basket(request.user)
    content = {'title': title, 'basket': basket}
    return render(request, 'mainapp/contact.html', content)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>

<body>
    <div class="container">
        {% block menu %}
            <div class="hero-white">
                <div class="header clearfix">
                    {% include 'mainapp/includes/inc_menu.html' %}
                </div>
            </div>
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>

    {% block footer %}
        <div class="footer">
             <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}

</body>
</html>

geekshop/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
		<div class="hero-white">
			<div class="header clearfix">
				{% block menu %}
                {% include 'mainapp/includes/inc_menu.html' %}
                {% endblock %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>

		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					<li><a href="{% url 'products:shop' %}" class="active">все</a></li>
					<li><a href="#">дом</a></li>
					<li><a href="#">офис</a></li>
					<li><a href="#">модерн</a></li>
					<li><a href="#">классика</a></li>
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p>
						<p>Отличное качество материалов
						позволит вам это.</p>
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
		<div class="hero">
			<h1>наши контакты </h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product-page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Страница продукта</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
</head>
<body>
{% for product in products %}
    <div class="block">
        <p>{{ product.name }}</p>
        <img src="/static/img/{{ product.image }}" alt="product">
        <p>{{ product.short_desc }}</p>
        <p>{{ product.description }}</p>
        <p>{{ product.price }}</p>
        <p>{{ product.quatity }}</p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
            заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
    </div>
{% endfor %}
</body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="static/img/{{ product.image }}"
                         alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#">
                            <img src="/static/img/{{ product.image }}" alt="вариант 1">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/static/img/{{ product.image }}" alt="вариант 2">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/static/img/{{ product.image }}" alt="вариант 3">
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
		<div class="details">
			<div class="links clearfix">
                {% include 'mainapp/includes/inc_categories_menu.html' %}
            </div>

            <div class="details-products">
                <div class="details-slider">
                    <div class="slider-product">
                        <img src="/media/{{ hot_product.image }}">
                    </div>
                    <div class="slider-control">
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                        </div>
                        <div class="block">
                            <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                        </div>
                    </div>
                </div>

                <div class="description">
                    <h3 class="big-bold">{{ hot_product.name }}</h3>
                    <h3 class="red">горячее предложение</h3>
                    <p class="price">{{ hot_product.price }} <span>руб</span></p>
                    <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                        заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                    <div class="description-text">
                        {{ hot_product.description }}
                    </div>
                </div>
            </div>



			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
                    <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
                </div>
                <div class="related-products clearfix">
                    {% for product in same_products %}
                        <div class="block">
                            <a href="{% url 'products:product' product.pk %}">
                                <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                                <div class="text">
                                    <img src="/static/img/icon-hover.png" alt="img">
                                    <h3>Категория:{{ product.category.name }}</h3>
                                    <h4>Название: {{ product.name }}</h4>
                                    <p>Описание: {{ product.description }} </p>
                                    <p>Цена: {{ product.price }} </p>
                                    <p>На складе: {{ product.quantity }} </p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

		<div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current"> страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/shop.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
		<div class="slider">
			<div class="header clearfix">
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix"></div>

			<div class="tab-content">
				{% for product in products %}
				    <div class="block">
					    <a href={% url 'products:product' product.pk %}><img src="/static/img/{{ product.image }}" alt="{{ product.short_desc }}">
						    <div class="text">
							    <h3>{{ product.category.name }}</h3>
							    <h4>{{ product.name }}</h4>
							    <p>{{ product.description }}</p>
						    </div>
					    </a>
				    </div>
				{% endfor %}
			</div>
		</div>

		<div class="clr"></div>
{% endblock %}